#!/bin/bash

# this Script For add user with username

if [ $UID -ne 0 ];
then
        echo "You must use Root Prifilage to run this Script (use sudo)"
fi

while true
do
        echo -n "Please Enter the group name that you need to delete it: "
        read groupname

        grep "^$groupname:" /etc/group &>/dev/null
        if [ $? -eq 0 ];
        then

		echo -n "Are you sure to delete this group ( yes,no ): "
		read op
		if [ $op = "yes" -o $op = "y" ];
		then
			groupdel $groupname &>/dev/null
			echo "Group '$groupname' is Deleted Successfully..!"
			break
		else
	
			echo "User deletion cancelled.."
			break
        	fi
	else
		echo "Group '$groupname' Dosen't Exist..."
	fi
done
