#!/usr/bin/env bash
# print_SHNOUDA.sh - show ASCII art in all colors

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
FUCHSIA='\033[0;95m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # Reset

# ASCII art
S[0]='  ____   _   _  _   _   _____   _   _  ____   ____    _    '
S[1]=' / ___| | | | || \ | | /  _  \ | \ | ||  _ \ |  _ \  / \   '
S[2]=' \___ \ | |_|_||  \| ||  / \  ||  \| || | | || | | |/ _ \  '
S[3]='  ___) || |_| || |\  ||  \_/  || |\  || |_| || |_| / ___ \ '
S[4]=' |____/ |_| |_||_| \_| \_____/ |_| \_||____/ |____/_/   \_\ '

colors=("$GREEN" "$YELLOW" "$RED" "$CYAN" "$FUCHSIA" "$PURPLE")

for i in "${!S[@]}"; do
  echo -e "${colors[$i]}${S[$i]}${NC}"
done

echo -e "\n"

echo -e "${RED}This ${YELLOW}script ${CYAN}was ${FUCHSIA}made ${GREEN}by ${PURPLE}S${FUCHSIA}h${YELLOW}n${CYAN}o${BLUE}u${GREEN}d${RED}a${NC}\n\n"

select var in "Add User" "Modify User" "Delete User" "List Users" "Add Group" "Modify Group" "Delete Group" "List Groups" "Disable User Account" "Enable User Account" "Change Password" "About" "exit"
do
#!/bin/bash

PS3="Please select an option: "

select var in "Add User" "Modify User" "Delete User" "List Users" \
              "Add Group" "Modify Group" "Delete Group" "List Groups" "Disable User" "Enable User" "Change Password" "About" "Exit"
do
    case $var in
        "Add User")
            	Ps3="Add User:> "
		echo "this script for add user"
		./scripts/useradd
            ;;
        "Modify User")
		echo "this script for Modify User"
		PS3="Modify Users:> "
		./scripts/deluser
            ;;
        "Delete User")
        	echo "this script for Delete User"
		PS3="Delete Users:> "
            ;;
        "List Users")
         	echo "this script for List Users"
		PS3="List Users:> "
            ;;
        "Add Group")
         	echo "this script for Add Group"
		PS3="Add groups:> "
            ;;
        "Modify Group")
         	echo "this script for Modify Group"
		PS3="Modify Group:> "
            ;;
        "Delete Group")
         	echo "this script for Delete Group"
		 PS3="Delete Group:> "
            ;;
        "List Groups")
          	echo "this script for List Groups"
		PS3="List Groups:> "
            ;;
        "Disable User")
         	echo "this script for Disable User"
		PS3="Disable User:> "
            ;;
        "Enable User")
           	echo "this script for Enable User"
		PS3="Enable User:> "
            ;;
        "Change Password")
            	echo "this script for Change Password"
		PS3="Change Password:> "
            ;;
        "About")
		PS3="About:> "
            ;;
        "Exit")
            echo "Exiting...!"
            break
            ;;
        *)
            echo "Invalid option, try again."
            ;;
    esac
done



done

