#!/bin/bash

#this script is use to look Account for user with username
if [ $UID -ne 0 ];
then
        echo "You must use Root Prifilage to run this Script (use sudo)"
fi

id "$username" &>/dev/null

while true
do
        echo -n "Please Enter the name of user that you need to Look his Account: "
        read username

        id "$username" &>/dev/null
        if [ $? -eq 0 ];
        then
		echo -n "Are you sure to unlock '$username' Account ( yes,no ): "
                read op
                if [ $op = "yes" -o $op = "y" ];
                then
                        passwd -l $username &>/dev/null
                        echo "$username Account is unlocked successfuly..!"
                        break
                else
                        echo "unLocking Accoun Cancled"
                        break
                fi
        else

                echo "this User Dosen't Exist to unlock his Account"
                break
        fi
done






